# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBranch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('address_street_1', models.CharField(max_length=200)),
                ('address_street_2', models.CharField(max_length=200)),
                ('address_town', models.CharField(max_length=200)),
                ('address_region', models.CharField(max_length=200)),
                ('address_postcode', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('trainee_feed_identifier', models.CharField(max_length=200, null=True, blank=True)),
                ('branch_notifications_to', models.CharField(max_length=200)),
                ('branch_resources_introduction', models.TextField(null=True, blank=True)),
                ('archived', models.IntegerField()),
                ('top_level', models.CharField(max_length=200)),
                ('extra_top_level', models.CharField(max_length=200)),
                ('feed_identifier', models.CharField(max_length=200, null=True, blank=True)),
                ('pending', models.IntegerField()),
            ],
            options={
                'db_table': 'core_branch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreBranding',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.IntegerField()),
                ('mm_welcome_text', models.TextField()),
                ('mm_slug', models.CharField(max_length=50)),
                ('noticeboard_label', models.CharField(max_length=255)),
                ('careers_label', models.CharField(max_length=255)),
                ('field_palette', models.TextField(db_column='_palette')),
                ('external_training_label', models.CharField(max_length=255)),
                ('competence_label', models.CharField(max_length=255)),
                ('appraisal_label', models.CharField(max_length=255)),
                ('noticeboard_label_plural', models.CharField(max_length=255)),
                ('careers_label_plural', models.CharField(max_length=255)),
                ('external_training_label_plural', models.CharField(max_length=255)),
                ('competence_label_plural', models.CharField(max_length=255)),
                ('appraisal_label_plural', models.CharField(max_length=255)),
                ('field_mobile_palette', models.TextField(db_column='_mobile_palette')),
            ],
            options={
                'db_table': 'core_branding',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreCareerpath',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('information_sheet_description', models.TextField()),
                ('information_sheet_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'core_careerpath',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('address_street_1', models.CharField(max_length=200)),
                ('address_street_2', models.CharField(max_length=200)),
                ('address_town', models.CharField(max_length=200)),
                ('address_region', models.CharField(max_length=200)),
                ('address_postcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('number_of_employees', models.CharField(max_length=20)),
                ('discount', models.DecimalField(max_digits=4, decimal_places=2)),
                ('notes', models.TextField()),
                ('is_simple_company', models.IntegerField()),
                ('simple_company_trainee_alert_count', models.IntegerField()),
                ('questionnaire_url', models.CharField(max_length=200)),
                ('trainee_feed_type', models.CharField(max_length=200, null=True, blank=True)),
                ('field_trainee_feed_settings', models.TextField(null=True, db_column='_trainee_feed_settings', blank=True)),
                ('simple_modules_enabled', models.IntegerField()),
                ('simple_module_active_limit', models.IntegerField(null=True, blank=True)),
                ('appraisals_enabled', models.IntegerField()),
                ('career_paths_enabled', models.IntegerField()),
                ('branch_resources_enabled', models.IntegerField()),
                ('self_service_custom_downloads_enabled', models.IntegerField()),
                ('self_service_custom_questions_enabled', models.IntegerField()),
                ('maximum_custom_questions', models.IntegerField()),
                ('branch_resources_introduction', models.TextField(null=True, blank=True)),
                ('scorm_enabled', models.IntegerField()),
                ('scorm_valid_days', models.IntegerField()),
                ('open_pdfs', models.IntegerField()),
                ('open_pdfs_pre_module', models.IntegerField()),
                ('top_level_enabled', models.IntegerField()),
                ('top_level_label', models.CharField(max_length=200)),
                ('region_label', models.CharField(max_length=200)),
                ('area_label', models.CharField(max_length=200)),
                ('departments_enabled', models.IntegerField()),
                ('extra_top_level_enabled', models.IntegerField()),
                ('extra_top_level_label', models.CharField(max_length=200)),
                ('hide_access_codes', models.IntegerField()),
                ('field_gkone_export_settings', models.TextField(null=True, db_column='_gkone_export_settings', blank=True)),
                ('slug', models.CharField(unique=True, max_length=50)),
                ('news_enabled', models.IntegerField()),
                ('competences_enabled', models.IntegerField()),
                ('dashboard_cache_enabled', models.IntegerField()),
                ('dashboard_cache_hours', models.IntegerField()),
                ('dashboard_cache_auto_update', models.IntegerField()),
                ('dashboard_cache_last_auto_updated', models.DateTimeField(null=True, blank=True)),
                ('external_training_enabled', models.IntegerField()),
                ('mm_view_appraisal_introduction', models.TextField(null=True, blank=True)),
                ('ms_appraisal_statement', models.TextField()),
                ('birtreports_enabled', models.IntegerField()),
                ('scorm_hosting_enabled', models.IntegerField()),
                ('mb_modules_enabled', models.IntegerField()),
                ('emailauth_enabled', models.IntegerField()),
                ('commencement_days_enabled', models.IntegerField()),
                ('default_commencement_days', models.IntegerField()),
                ('override_platform_branding', models.IntegerField()),
                ('override_platform_name', models.CharField(max_length=200, null=True, blank=True)),
                ('override_platform_from_email', models.CharField(max_length=75, null=True, blank=True)),
                ('override_platform_mm_link', models.CharField(max_length=200, null=True, blank=True)),
                ('override_platform_ms_link', models.CharField(max_length=200, null=True, blank=True)),
                ('department_label', models.CharField(max_length=200)),
                ('branch_label', models.CharField(max_length=200)),
                ('top_level_label_plural', models.CharField(max_length=200)),
                ('extra_top_level_label_plural', models.CharField(max_length=200)),
                ('region_label_plural', models.CharField(max_length=200)),
                ('area_label_plural', models.CharField(max_length=200)),
                ('department_label_plural', models.CharField(max_length=200)),
                ('branch_label_plural', models.CharField(max_length=200)),
                ('allow_bulk_trainee_upload', models.IntegerField()),
                ('allow_trainee_external_identifiers', models.IntegerField()),
                ('require_trainee_external_identifiers', models.IntegerField()),
                ('trainee_import_unique_id', models.CharField(max_length=200)),
                ('field_results_export_settings', models.TextField(null=True, db_column='_results_export_settings', blank=True)),
                ('is_pending', models.IntegerField()),
                ('mobile_app_enabled', models.IntegerField()),
                ('training_calendar_enabled', models.IntegerField()),
                ('cloud2_enabled', models.IntegerField()),
                ('account_manager', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'db_table': 'core_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreDepartment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(to='flow_hosp_live.CoreCompany')),
            ],
            options={
                'db_table': 'core_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreIndividual',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('address_street_1', models.CharField(max_length=200)),
                ('address_street_2', models.CharField(max_length=200)),
                ('address_town', models.CharField(max_length=200)),
                ('address_region', models.CharField(max_length=200)),
                ('address_postcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('identification_code', models.CharField(max_length=20, unique=True, null=True, blank=True)),
                ('ila_token', models.CharField(max_length=255)),
                ('ila_account_holder', models.IntegerField()),
                ('account_manager', models.ForeignKey(related_name='coreIndividualAccountManager', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'db_table': 'core_individual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreJurisdiction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(to='flow_hosp_live.CoreCompany')),
            ],
            options={
                'db_table': 'core_jurisdiction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreTrainee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('email', models.CharField(max_length=75)),
                ('mobile_number', models.CharField(max_length=20)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField()),
                ('orderable_name', models.CharField(max_length=255)),
                ('identification_code', models.CharField(max_length=20, unique=True, null=True, blank=True)),
                ('job_title', models.CharField(max_length=50)),
                ('training_notes', models.TextField()),
                ('taken_questionnaire', models.IntegerField()),
                ('ila_token', models.CharField(max_length=255)),
                ('ila_account_holder', models.IntegerField()),
                ('marked_as_leaver', models.DateTimeField(null=True, blank=True)),
                ('sex', models.CharField(max_length=10)),
                ('training_performance', models.TextField()),
                ('branch', models.ForeignKey(to='flow_hosp_live.CoreBranch')),
                ('career_path', models.ForeignKey(blank=True, to='flow_hosp_live.CoreCareerpath', null=True)),
                ('department', models.ForeignKey(blank=True, to='flow_hosp_live.CoreDepartment', null=True)),
                ('field_copied_from_inidividual', models.ForeignKey(db_column='_copied_from_inidividual_id', blank=True, to='flow_hosp_live.CoreIndividual', null=True)),
                ('field_copied_from_trainee', models.ForeignKey(db_column='_copied_from_trainee_id', blank=True, to='flow_hosp_live.CoreTrainee', null=True)),
            ],
            options={
                'db_table': 'core_trainee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlowCoreColourscheme',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField()),
                ('removed', models.DateTimeField(null=True, blank=True)),
                ('last_modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('highlight_text_colour', models.CharField(max_length=6)),
                ('base_text_colour', models.CharField(max_length=6)),
                ('footer_text_colour', models.CharField(max_length=6)),
                ('button_text_colour', models.CharField(max_length=6)),
                ('textbox_border', models.CharField(max_length=6)),
                ('textbox_background_colour_a', models.CharField(max_length=6)),
                ('textbox_background_colour_b', models.CharField(max_length=6)),
                ('html_background_colour', models.CharField(max_length=6)),
                ('html_text_colour', models.CharField(max_length=6)),
                ('popup_heading_left', models.CharField(max_length=6)),
                ('popup_heading_right', models.CharField(max_length=6)),
                ('created_by', models.ForeignKey(related_name='flowCoreColourschemeCreated', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('removed_by', models.ForeignKey(related_name='flowCoreColourschemeRemoved', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'db_table': 'flow_core_colourscheme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResellerReseller',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('reseller_type', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, to='flow_hosp_live.ResellerReseller', null=True)),
            ],
            options={
                'db_table': 'reseller_reseller',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coreindividual',
            name='copied_from',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.CoreTrainee', null=True),
        ),
        migrations.AddField(
            model_name='coreindividual',
            name='user',
            field=models.OneToOneField(related_name='coreIndividualUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corecompany',
            name='reseller',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.ResellerReseller', null=True),
        ),
        migrations.AddField(
            model_name='corecompany',
            name='simple_module_colour_scheme',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.FlowCoreColourscheme', null=True),
        ),
        migrations.AddField(
            model_name='corecareerpath',
            name='company',
            field=models.ForeignKey(to='flow_hosp_live.CoreCompany'),
        ),
        migrations.AddField(
            model_name='corebranding',
            name='company',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.CoreCompany', null=True),
        ),
        migrations.AddField(
            model_name='corebranch',
            name='branding',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.CoreBranding', null=True),
        ),
        migrations.AddField(
            model_name='corebranch',
            name='company',
            field=models.ForeignKey(to='flow_hosp_live.CoreCompany'),
        ),
        migrations.AddField(
            model_name='corebranch',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, to='flow_hosp_live.CoreJurisdiction', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='corejurisdiction',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='corecareerpath',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='corebranch',
            unique_together=set([('feed_identifier', 'company')]),
        ),
    ]
